# Use custom format
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$all\
$line_break\
$character"""

[directory]
style = "%COLORCODE"
read_only = " ğ‘Ÿğ‘’ğ‘ğ‘‘ ğ‘œğ‘›ğ‘™ğ‘¦"
truncation_length = 4
truncate_to_repo = true

[character]
success_symbol = "[â¯](#3684DD)"
error_symbol = "[âœ—](#E53935)"
vicmd_symbol = "[â®](#4CAF50)"

[git_branch]
symbol = "â‡  "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[conda]
symbol = "ğŸ“¦ "
format = "[â€¢](bold green) is [$symbol$version]($style) "

[package]
symbol = "ğŸ“¦ "
format = "[â€¢](bold green) is [$symbol$version]($style) "

[docker_context]
disabled = false
symbol = "ğŸ³ "
format = "[â€¢](bold green) via [$symbol$context]($style) "
style = "bold blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

[golang]
symbol = "ğŸ¹ "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[java]
symbol = "â˜• "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[perl]
symbol = "ğŸª "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[php]
symbol = "ğŸ˜ "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[python]
symbol = "ğŸ "
format = "[â€¢](bold green) via [$symbol$version]($style) "
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = "ğŸ’ "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[rust]
symbol = "ğŸ¦€ "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[scala]
symbol = "ğŸ”º "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[swift]
symbol = "ğŸ¦… "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[haskell]
symbol = "Î» "
format = "[â€¢](bold green) via [$symbol$version]($style) "

[nodejs]
format = "via [ğŸŸ¢ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
