format = """$directory\
$git_branch\
$git_metrics\
$cmd_duration\
$line_break\
$character"""

command_timeout = 200
add_newline = false

[directory]
style = "%COLORCODE"
read_only = " ğ‘Ÿğ‘’ğ‘ğ‘‘ ğ‘œğ‘›ğ‘™ğ‘¦"
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = "â‡  "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
min_time = 2000
format = "[â€¢](bold green) took [$duration]($style)"

[character]
success_symbol = "[â¯](#3684DD)"
error_symbol = "[âœ—](#E53935)"
vicmd_symbol = "[â®](#4CAF50)"
